version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ai_test_db
    environment:
      POSTGRES_DB: ai_test
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./migrations:/migrations
    ports:
      - "5432:5432"
    networks:
      - ai_test_network

networks:
  ai_test_network:
    driver: bridge